trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Versionize
  displayName: Adding Versionize to the build pipeline
  jobs:
  - job: AddVersionize
    displayName: Add Versionize
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: |
          dotnet tool install --global Versionize
          versionize
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Docker Build and Push 
      inputs:
        containerRegistry: 'Devops Docker Service Connection'
        repository: 'swarooprooney/azuredevops'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
- stage: Provision
  displayName: 'tf state to azure'
  dependsOn: Build
  jobs:
    - job: Provision
      displayName: 'Provision container instance'
      pool:
        vmImage: 'ubuntu-latest'
      variables:
      - group: TerraformServicePrincipleVars
      steps:
        - script: |
            set -e 
            terraform init -input=false
            terraform apply -input=false -auto-approve
          name: 'Runterraform'
          displayName: 'Run terraform script'
          env :
            ARM_CLIENT_ID : $(ARM_CLIENT_ID)
            ARM_CLIENT_SECRET : $(ARM_CLIENT_SECRET)
            ARM_SUBSCRIPTION_ID : $(ARM_SUBSCRIPTION_ID)
            ARM_TENANT_ID : $(ARM_TENANT_ID)
            TF_VAR_BUILD_ID : $(Build.BuildId)